[openrouter]
api_key = "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"
base_url = "https://openrouter.ai/api/v1"
site_url = "http://localhost:8000"  # or your production URL
site_name = "Stat Analyzer"

[secrets]
